### PR TITLE
Adding persistence to FFB Strength adjustments between loads.

### PR DESCRIPTION
**Pull request by adamgp**
Hi, I'm committing this without testing as I'm having difficulty building post updating to the latest changes (where the Demul changeVolume function was introduced), see below:

image

I'm hoping you can peer review the code and modify as you see fit.

**The basic concept** is to store the FFB Strength adjustments the user makes back to the FFBPlugin.ini so that upon next game load this strength is recalled. Without affecting the default MaxForce strength allowing resetting back to the original strength always.

Persistent values are loaded just after the FFB Strength adjustment loop (perhaps this should be before), if this value has never been set before.

Thanks!

### CODE REVIEW

**Comment by Boomslangnz** [comment]
Yea I got changes I havent commited yet

Easy to fix though

**Comment by adamgp** [comment]
Ha, yea - I just renamed the function. Sorry, it was very late last night and that thought never crossed my mind! I'll test this evening and report back.

**Comment by Boomslangnz** [comment]
Just add static infront of them if needed for now1

**Comment by adamgp** [comment]
Just tested and all works as expected. Ready to merge.

**Pull request merged**
